In [31]:
from scipy import stats
import numpy as np
import pandas as pd

df = pd.read_csv("SSBendline.csv")
df.drop(columns=df.columns[:17], 
        axis=1, 
        inplace=True)

df = df.fillna(0)
df = df.drop(df.index[range(2)])

sum_column = (df.Q23_1).astype(int) + (df.Q23_2).astype(int) + (df.Q23_3).astype(int) + (df.Q23_4).astype(int)
mean = sum_column / 4
df["efficacy"] = mean

crosstab = pd.crosstab(df['Q26'], df['Q31'])
crosstab1 = pd.crosstab(df['Q26'], df['Q12_1'])
crosstab2 = pd.crosstab(df['Q26'], df['Q19'])



In [30]:
#message exposure and intention
stats.chi2_contingency(crosstab)

(116.5359238778003,
 2.5490159187046052e-20,
 10,
 array([[ 4.28813559,  0.37288136,  1.30508475,  4.10169492,  8.20338983,
          3.72881356],
        [ 7.60169492,  0.66101695,  2.31355932,  7.27118644, 14.54237288,
          6.61016949],
        [11.11016949,  0.96610169,  3.38135593, 10.62711864, 21.25423729,
          9.66101695]]))

In [16]:
#message exposure and perceived importance to reduce consumption
stats.chi2_contingency(crosstab1)

(100.62806321134975,
 4.0798267245558785e-17,
 10,
 array([[ 3.91525424,  0.55932203,  2.61016949,  4.10169492,  7.27118644,
          3.54237288],
        [ 6.94067797,  0.99152542,  4.62711864,  7.27118644, 12.88983051,
          6.27966102],
        [10.1440678 ,  1.44915254,  6.76271186, 10.62711864, 18.83898305,
          9.1779661 ]]))

In [12]:
#message exposure and intention of drinking with friends 
stats.chi2_contingency(crosstab2)

(103.41720811241564,
 1.125938087705341e-17,
 10,
 array([[ 3.54237288,  1.11864407,  1.86440678,  5.03389831,  7.6440678 ,
          2.79661017],
        [ 6.27966102,  1.98305085,  3.30508475,  8.92372881, 13.55084746,
          4.95762712],
        [ 9.1779661 ,  2.89830508,  4.83050847, 13.04237288, 19.80508475,
          7.24576271]]))

In [8]:
#message exposure and SSB consumption in the past 7 days
exposure = df.loc[df['Q26'] == "1", 'Q16'].value_counts()
no_exposure = df.loc[df['Q26'] == "2", 'Q16'].value_counts()
stats.ttest_ind(a=exposure, b=no_exposure, equal_var=True)

Ttest_indResult(statistic=-1.6712436347422488, pvalue=0.11297848435848984)

In [20]:
#message exposure and perceived self efficiency
exposure_ef = df.loc[df['Q26'] == "1", 'efficacy']
no_exposure_ef = df.loc[df['Q26'] == "2", 'efficacy']
stats.ttest_ind(a=exposure_ef, b=no_exposure_ef, equal_var=True)

Ttest_indResult(statistic=1.5083873389008373, pvalue=0.13480923297150993)

In [24]:
#instagram follows and SSB consumption in the past 7 days
exposure = df.loc[df['Q32'] == "1", 'Q16'].value_counts()
no_exposure = df.loc[df['Q32'] == "2", 'Q16'].value_counts()
stats.ttest_ind(a=exposure, b=no_exposure, equal_var=True)

Ttest_indResult(statistic=-2.364270611137305, pvalue=0.03197791743247977)

In [25]:
#instagram follows and perceived importance to reduce consumption
crosstab3 = pd.crosstab(df['Q32'], df['Q12_1'])
stats.chi2_contingency(crosstab3)

(95.21862618441807,
 4.912889576536513e-16,
 10,
 array([[ 4.09322034,  0.58474576,  2.72881356,  4.28813559,  7.60169492,
          3.70338983],
        [ 3.91525424,  0.55932203,  2.61016949,  4.10169492,  7.27118644,
          3.54237288],
        [12.99152542,  1.8559322 ,  8.66101695, 13.61016949, 24.12711864,
         11.75423729]]))